[project]
name = "git-citation2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Déborah", email = "deborah.oussar@etu.univ-tours.fr" }
]
requires-python = ">=3.14"
dependencies = [
    "pyfiglet>=1.0.4",
    "rich>=15.0.0",
]

[project.scripts]
git-citation2 = "git_citation2:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
